name: openai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - openai
    - pandas
    - numpy
    - plotly
    - scikit-learn
    - torch
    - matplotlib
    - pydantic
